# Generated by Django 5.1.7 on 2025-03-30 13:41

import ProgressBar.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=5)),
                ('public_id', models.CharField(default=ProgressBar.models.generate_unique_id, editable=False, max_length=9, unique=True)),
                ('admin_id', models.CharField(default=ProgressBar.models.generate_random_string, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ProgressBar.progress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
