# Generated by Django 5.1.7 on 2025-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressBar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='name',
            field=models.CharField(default='Lorem psum', max_length=255),
        ),
    ]
