# Generated by Django 5.1.7 on 2025-03-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressBar', '0002_progress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='last_24h_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_31_days_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='percentage_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='progress',
            name='total_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
