# Generated by Django 5.1.7 on 2025-03-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressBar', '0003_progress_last_24h_visits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='last_24h_visits',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='last_31_days_visits',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='percentage_history',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='total_visits',
        ),
    ]
