# Generated by Django 5.1.7 on 2025-03-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressBar', '0004_remove_progress_last_24h_visits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ProgressBar.progress')),
            ],
        ),
    ]
